---
# - name: Configure all adapters whose names begin with Ethernet to use DHCP-assigned DNS values
#   win_dns_client:
#     adapter_names: 'Ethernet*'
#     ipv4_addresses:
#       - 10.0.3.211


# - name: Add domain
#   win_domain_membership:
#     dns_domain_name: kom.keppelgroup.com
#     hostname: DNSDOMAINTEST
#     domain_admin_user: service_sc_automation@kom.keppelgroup.com
#     domain_admin_password: C1sc0@123!@#
#     domain_ou_path: "Infrastructure Servers,DC=kom,DC=keppelgroup,DC=com"
#     state: domain
#   register: domain_state

- name: domain state
  debug:
    msg: "{{Test playbook}}"

# - win_reboot:
#   when: domain_state.reboot_required